class FishSpec {
  const FishSpec({
    required this.level,
    required this.name,
    required this.length,
    required this.speed,
    required this.damage,
    required this.xp,
    required this.score,
    required this.turnRate,
    required this.chaseChance,
    this.boss = false,
  });

  final int level;
  final String name;
  final double length;
  final double speed;
  final int damage;
  final int xp;
  final int score;
  final double turnRate;
  final double chaseChance;
  final bool boss;
}

class FishSpecs {
  static const int maxLevel = 12;

  static const List<FishSpec> all = [
    FishSpec(
      level: 1,
      name: '沙丁魚',
      length: 38,
      speed: 78,
      damage: 6,
      xp: 15,
      score: 10,
      turnRate: 3.4,
      chaseChance: 0,
    ),
    FishSpec(
      level: 2,
      name: '雀鯛',
      length: 48,
      speed: 92,
      damage: 8,
      xp: 20,
      score: 20,
      turnRate: 3.3,
      chaseChance: 0,
    ),
    FishSpec(
      level: 3,
      name: '小丑魚',
      length: 58,
      speed: 106,
      damage: 10,
      xp: 25,
      score: 30,
      turnRate: 3.2,
      chaseChance: .05,
    ),
    FishSpec(
      level: 4,
      name: '藍倒吊',
      length: 70,
      speed: 120,
      damage: 12,
      xp: 30,
      score: 40,
      turnRate: 3.1,
      chaseChance: .12,
    ),
    FishSpec(
      level: 5,
      name: '蝶魚',
      length: 84,
      speed: 135,
      damage: 16,
      xp: 36,
      score: 55,
      turnRate: 3.0,
      chaseChance: .25,
    ),
    FishSpec(
      level: 6,
      name: '鯖魚',
      length: 100,
      speed: 150,
      damage: 20,
      xp: 43,
      score: 70,
      turnRate: 2.9,
      chaseChance: .32,
    ),
    FishSpec(
      level: 7,
      name: '真鯛',
      length: 118,
      speed: 166,
      damage: 24,
      xp: 51,
      score: 90,
      turnRate: 2.75,
      chaseChance: .38,
    ),
    FishSpec(
      level: 8,
      name: '鰺魚',
      length: 138,
      speed: 182,
      damage: 28,
      xp: 60,
      score: 115,
      turnRate: 2.6,
      chaseChance: .44,
    ),
    FishSpec(
      level: 9,
      name: '鮪魚',
      length: 160,
      speed: 198,
      damage: 32,
      xp: 70,
      score: 145,
      turnRate: 2.45,
      chaseChance: .5,
    ),
    FishSpec(
      level: 10,
      name: '旗魚',
      length: 184,
      speed: 216,
      damage: 36,
      xp: 82,
      score: 180,
      turnRate: 2.3,
      chaseChance: .56,
    ),
    FishSpec(
      level: 11,
      name: '鬼頭刀',
      length: 210,
      speed: 234,
      damage: 41,
      xp: 96,
      score: 220,
      turnRate: 2.15,
      chaseChance: .62,
    ),
    FishSpec(
      level: 12,
      name: '帆魚',
      length: 238,
      speed: 252,
      damage: 47,
      xp: 112,
      score: 270,
      turnRate: 2.0,
      chaseChance: .68,
    ),
    FishSpec(
      level: 13,
      name: '大白鯊',
      length: 270,
      speed: 270,
      damage: 54,
      xp: 130,
      score: 330,
      turnRate: 1.85,
      chaseChance: .74,
    ),
    FishSpec(
      level: 14,
      name: '虎鯊',
      length: 306,
      speed: 288,
      damage: 62,
      xp: 152,
      score: 400,
      turnRate: 1.7,
      chaseChance: .8,
    ),
    FishSpec(
      level: 15,
      name: '抹香鯨',
      length: 346,
      speed: 306,
      damage: 72,
      xp: 178,
      score: 490,
      turnRate: 1.55,
      chaseChance: .85,
    ),
    FishSpec(
      level: 16,
      name: '巨口鯊',
      length: 392,
      speed: 330,
      damage: 84,
      xp: 210,
      score: 610,
      turnRate: 1.45,
      chaseChance: .9,
    ),
    FishSpec(
      level: 17,
      name: '鄧氏魚',
      length: 444,
      speed: 312,
      damage: 100,
      xp: 250,
      score: 760,
      turnRate: 1.25,
      chaseChance: .92,
    ),
    FishSpec(
      level: 18,
      name: '滄龍',
      length: 506,
      speed: 340,
      damage: 125,
      xp: 320,
      score: 1000,
      turnRate: 1.1,
      chaseChance: .95,
      boss: true,
    ),
  ];

  static FishSpec byLevel(int level) {
    return all[level.clamp(1, maxLevel) - 1];
  }
}
